### PR TITLE
fix(renderer): allow unicode for no-escape variables

### PR DESCRIPTION
**Pull request by lksnmnn**
## Issue
See Issue https://github.com/noahmorrison/chevron/issues/28 for more details.

## Changes
- Add unicode parsing for 'no-escape' case
- Add test case for parsing unicode  without escaping HTML

### CODE REVIEW

**Comment by lksnmnn** [comment]
I am not familiar with Tox so I do not know how to fix the failing CI job, but it should have nothing to do with my changes.

**Comment by lksnmnn** [comment]
@noahmorrison Are you still maintaining this package? I am happy to help.

**Comment by samuelcolvin** [comment]
In the past @noahmorrison responded and help eventually.

We too are actively using this repr so are happy to help maintain.

**Comment by lksnmnn** [comment]
It seems he can cross out the first two TODOs in the Readme.md ;)

**Comment by noahmorrison** [comment]
Hey guys, I have [no idea](https://travis-ci.org/noahmorrison/chevron/jobs/390379265#L525) why tox failed. It only failed on python 3.3 which I tried on my local machine and it worked fine.

Merging this fix in, thanks for the unittest.

Still happy to see this project being used :)

**Pull request merged**
